"use client";

import { Download,Eye,Printer } from "lucide-react";
import { Badge,type BadgeProps } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatCurrency,formatDate } from "@/lib/utils";
export interface InvoiceRow{id:string;invoiceNumber:string;invoiceDate:Date|string;status:"DRAFT"|"GENERATED"|"SENT"|"PAID"|"CANCELLED";grandTotal:number;paidAmount:number;pendingAmount:number;pdfUrl:string|null;trip:{tripNumber:string;source:string;destination:string;vehicle:{number:string};driver:{name:string}|null}}
const variants:Record<InvoiceRow["status"],BadgeProps["variant"]>={DRAFT:"secondary",GENERATED:"info",SENT:"warning",PAID:"success",CANCELLED:"destructive"};
export function InvoicesTable({data}:{data:InvoiceRow[]}){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{["Invoice","Date","Trip","Vehicle","Route","Total","Pending","Status",""].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{data.map(x=><tr key={x.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{x.invoiceNumber}</td><td className="px-4 py-3">{formatDate(x.invoiceDate)}</td><td className="px-4 py-3">{x.trip.tripNumber}</td><td className="px-4 py-3">{x.trip.vehicle.number}</td><td className="px-4 py-3">{x.trip.source} → {x.trip.destination}</td><td className="px-4 py-3">{formatCurrency(x.grandTotal)}</td><td className="px-4 py-3 text-amber-700">{formatCurrency(x.pendingAmount)}</td><td className="px-4 py-3"><Badge variant={variants[x.status]}>{x.status}</Badge></td><td className="flex justify-end gap-1 px-4 py-3"><Button size="icon" variant="ghost" title="View" onClick={()=>location.assign(`/invoices/${x.id}`)}><Eye className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Print" onClick={()=>{location.assign(`/invoices/${x.id}?print=1`)}}><Printer className="h-4 w-4"/></Button>{x.pdfUrl&&<Button size="icon" variant="ghost" title="Download PDF" onClick={()=>window.open(x.pdfUrl!,"_blank")}><Download className="h-4 w-4"/></Button>}</td></tr>)}</tbody></table></div>}
